from enum import Enum
from dataclasses import dataclass


class TokenType(Enum):
    """Enumeration of Symbol types"""
    NUMBER      =   0
    OPERATOR    =   1
    LPAREN      =   2
    RPAREN      =   3


@dataclass
class Token:
    """Symbols generated by lexer"""
    type: TokenType
    value: any = None
    preced: int = 0     # Precedence

    def __repr__(self):
        s = ""
        if self.value is not None:
            s += f"({self.type.name}"
            if self.preced:
                s += f"_{self.preced}"
            s += f": {self.value})"

        return s
